export const teams=[
 {id:'reef',name:'Coral Keepers',mode:'RESEARCHING',color:'#5bafaa',x:-10,z:5,topic:'How could we design a careful coral restoration pilot?',brief:'Three researchers compare coral resilience, habitat conditions, and what a pilot could measure.',ideas:['Coral resilience','Water conditions','Pilot monitoring','Evidence gaps'],talk:[['Mira · Investigator','Let’s separate our observations from assumptions. Water conditions and coral survival need to be tracked together.'],['Otto · Reviewer','Agreed. A connection on our map is a hypothesis, not proof that one factor causes another.'],['Pearl · Synthesizer','I’ve connected monitoring to the pilot design. Our shared bubble now keeps both the idea and its uncertainty.']]},
 {id:'learning',name:'Learning Lagoon',mode:'DISCUSSING',color:'#bf93c7',x:10,z:5,topic:'How can a classroom research pilot include learners with different needs?',brief:'A teacher, designer, and reviewer are shaping an inclusive learning experiment.',ideas:['Accessible activities','Teacher workload','Learning checks','Student feedback'],talk:[['Luma · Teacher','Can we keep the pilot to one familiar lesson, with an equivalent activity for students who need it?'],['Ink · Designer','Yes. I’m connecting accessibility to the assessment, so we measure the same learning goal.'],['Nori · Reviewer','Let’s retain student feedback alongside the scores. Those are different kinds of evidence.']]},
 {id:'studio',name:'Maker Cove',mode:'COLLABORATING',color:'#e6ae71',x:-10,z:-13,topic:'How should we prototype an underwater knowledge garden?',brief:'A small product team explores how to make research approachable, playful, and easy to revisit.',ideas:['Clay interaction','Spatial navigation','Shared bubbles','Readable labels'],talk:[['Pip · Designer','The world can be playful, but the research needs a clear place to live. Each team gets a shared bubble.'],['Finn · Builder','I’ll connect the source cards to the graph nodes. Selecting either should reveal the retained note.'],['Tess · Strategist','Let’s share our navigation ideas with the archive team, then keep the original authors attached.']]},
 {id:'archive',name:'Memory Meadow',mode:'COMBINING KNOWLEDGE',color:'#8daacb',x:10,z:-13,topic:'How can teams retain provenance while combining research?',brief:'An archive team connects ideas across projects without erasing where each one came from.',ideas:['Source provenance','Related concepts','Retained notes','Cross-team links'],talk:[['Sage · Archivist','A useful memory includes the original source, the retained note, and the team that added it.'],['Dot · Investigator','When two teams share knowledge, we should preserve both origins instead of pretending it was one discovery.'],['Kelp · Reviewer','This garden’s graph is an illustration. Similar positions are not vector-search results; every connection here is authored.']]}
];
export const references={
 reef:{title:'National Coral Reef Monitoring Program',publisher:'NOAA',url:'https://www.coralreef.noaa.gov/topics/national-coral-reef-monitoring-program',note:'Official overview of NOAA’s long-term coral reef monitoring program. A reference to explore, not evidence for every claim in the scripted conversation.'},
 learning:{title:'WCAG 2 at a Glance',publisher:'W3C Web Accessibility Initiative',url:'https://www.w3.org/WAI/standards-guidelines/wcag/glance/',note:'Overview of web accessibility principles and guidelines. Relevant background for accessible digital activities, not a study of classroom learning outcomes.'},
 studio:{title:'WebGPURenderer documentation',publisher:'Three.js',url:'https://threejs.org/docs/pages/WebGPURenderer.html',note:'Primary renderer documentation describing WebGPU support and WebGL 2 fallback. Reference material for the garden implementation.'},
 archive:{title:'PROV-Overview',publisher:'W3C',url:'https://www.w3.org/TR/prov-overview/',note:'Overview of the PROV family of documents for representing provenance and exchanging information about data origins.'}
};
