import {swimDirection,movementKey} from './octopus-control.js';
import {navigatorVoice} from './navigator-voice.js';
import {clayGrab} from './clay-grab.js?v=attached3';
import {clayOcean} from './clay-ocean.js';
import {mountMusic} from './music.js?v=claypods1';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {makeClayAgent} from './clay-agent.js?swim=2';
import {swimArm} from './fidelity.js?swim=2';
import {clayTexture,clayAlbedo,reflectionEnvironment} from './clay-texture.js';
import {savedResearch} from './research-store.js?v=home2';
const $=id=>document.getElementById(id);
mountMusic($('musicToggle'),'reef');const voice=navigatorVoice({after:$('musicToggle')});$('gardenControls').onclick=()=>{const open=document.querySelector('.travel').classList.toggle('expanded');$('gardenControls').setAttribute('aria-expanded',String(open));};
import {teams,references} from './garden-data.js';
const STORE='octopi-garden-knowledge-v1';let shared={};try{shared=JSON.parse(localStorage.getItem(STORE)||'{}');}catch{}
for(const team of teams){team.nodes=team.ideas.map((title,i)=>({id:team.id+'-'+i,title,type:i===0?'source':'idea',origin:team.name,note:i===0?'Illustrative starting material for this demo, not a retrieved publication.':team.talk[i%3][1]}));team.links=[[0,1],[0,2],[1,3],[2,3]];team.added=Array.isArray(shared[team.id])?shared[team.id].filter(n=>n&&typeof n.id==='string'&&typeof n.title==='string').slice(0,24):[];}
for(const team of teams){const ref=references[team.id];Object.assign(team.nodes[0],ref,{kind:'Reference page',citation:ref.publisher+'. '+ref.title+'. '+ref.url});
 for(const [label,value] of [['Publisher',ref.publisher],['URL',ref.url],['Source type','Official documentation']]){const id=team.nodes.length;team.nodes.push({id:team.id+'-meta-'+id,title:label+': '+value,type:'metadata',origin:team.name,note:value,url:ref.url,publisher:ref.publisher,citation:ref.publisher+'. '+ref.title+'. '+ref.url});team.links.push([0,id]);}
}
// Restore reference metadata on older shared demo nodes without discarding saved notes.
for(const team of teams)team.added=team.added.map(n=>{const canonical=teams.flatMap(t=>t.nodes).find(x=>x.id===n.id);return canonical?{...canonical,type:'shared'}:n;});
// Real locally retained records are distinguished from the authored demo notes.
for(const record of savedResearch().filter(r=>r.kind==='Live research').slice(0,3)){
 const node={id:'saved-'+record.id,title:record.title,type:'shared',origin:'Your saved research',note:(record.summary||record.question).slice(0,1600)};
 if(!teams[3].added.some(n=>n.id===node.id))teams[3].added.push(node);
}
const scene=new THREE.Scene();scene.background=new THREE.Color('#83bdc9');scene.fog=new THREE.FogExp2('#83bdc9',.007);
const renderer=new THREE.WebGPURenderer({canvas:$('world'),antialias:true,alpha:false});
await renderer.init();$('renderMode').textContent=renderer.backend.isWebGPUBackend?'WebGPU · reflective lighting':'WebGL 2 · reflective lighting';scene.environment=reflectionEnvironment();scene.environmentIntensity=.7;
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,160);camera.position.set(30,31,41);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,-3);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=65;controls.maxPolarAngle=Math.PI*.48;controls.minPolarAngle=.18;
scene.add(new THREE.HemisphereLight('#e2fff4','#65848d',1.8));const sun=new THREE.DirectionalLight('#fff5d4',2.2);sun.position.set(-12,24,18);scene.add(sun);renderer.shadowMap.enabled=true;sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:75});sun.shadow.bias=-.001;sun.shadow.normalBias=.05;const fill=new THREE.DirectionalLight('#81dbee',1.6);fill.position.set(14,10,-25);scene.add(fill);
const terrainTexture=clayTexture(22),propTexture=clayTexture(2.5),propAlbedo=clayAlbedo(propTexture);const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.9,map:propAlbedo,bumpMap:propTexture,bumpScale:.14});const sand=mat('#dcd6b5');sand.bumpMap=terrainTexture;sand.map=clayAlbedo(terrainTexture);sand.bumpScale=.5;const ground=new THREE.Mesh(new THREE.PlaneGeometry(140,140,128,128),sand);ground.rotation.x=-Math.PI/2;ground.position.y=-.3;ground.receiveShadow=true;scene.add(ground);const gp=ground.geometry.attributes.position;for(let i=0;i<gp.count;i++){const x=gp.getX(i),y=gp.getY(i),r=Math.hypot(x,y);gp.setZ(i,-Math.max(0,r-39)*1.2);}ground.geometry.computeVertexNormals();
let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const movable=[];
const ocean=clayOcean(scene);
const sphereGeo=new THREE.SphereGeometry(1,20,14),coralMats=['#ee6ca8','#ffb347','#2cd5b8','#aa88f4'].map(mat);
function blob(parent,x,y,z,sx,sy,sz,m){const mesh=new THREE.Mesh(sphereGeo,m);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.receiveShadow=true;parent.add(mesh);if(parent===scene&&sx<3){mesh.name='Clay pebble';movable.push(mesh);}return mesh;}
for(let i=0;i<115;i++){const x=(rand()-.5)*72,z=(rand()-.5)*65;blob(scene,x,-.05,z,.4+rand()*1.3,.2+rand()*.6,.4+rand(),mat(i%2?'#b3c6bf':'#a3bfc1'));}
function coral(x,z,color){const group=new THREE.Group();group.position.set(x,0,z);scene.add(group);for(let j=0;j<5;j++){const height=.6+rand()*1.7;const branch=blob(group,(rand()-.5)*1.5,height/2,(rand()-.5),.18,height/2,.18,color);branch.rotation.z=(rand()-.5)*.8;blob(group,branch.position.x+.3,height*.65,branch.position.z,.42,.13,.15,color).rotation.z=.7;}group.name='Clay coral';movable.push(group);return group;}
for(const t of teams){const patch=blob(scene,t.x,-.2,t.z,6,.25,5.5,mat('#e9dfba'));for(let j=0;j<9;j++){const a=j/9*Math.PI*2;coral(t.x+Math.cos(a)*5.5,t.z+Math.sin(a)*5,coralMats[j%4]);}}
for(let j=0;j<20;j++)coral((rand()-.5)*65,(rand()-.5)*55,coralMats[j%4]);
const octopi=[],pickables=[],teamGraphs=[],nodeColors={source:'#6fc1d4',idea:'#edbd75',shared:'#ba91d2',metadata:'#a8cfa2'};
const nodeGeo=new THREE.SphereGeometry(.14,16,12);const edgeMaterial=new THREE.LineBasicMaterial({color:'#4b909d',transparent:true,opacity:.75});
function allNodes(t){return [...t.nodes,...t.added];}
function graphFor(team){
 const root=new THREE.Group();root.position.set(team.x,4.5,team.z);scene.add(root);
 const shell=new THREE.Mesh(new THREE.SphereGeometry(2.05,36,24),new THREE.MeshPhysicalMaterial({color:team.color,transparent:true,opacity:.24,roughness:.08,metalness:.18,clearcoat:1,clearcoatRoughness:.06,iridescence:.55,iridescenceIOR:1.3,envMapIntensity:1.5,depthWrite:false,side:THREE.FrontSide}));root.add(shell);shell.userData.team=team;pickables.push(shell);
 const rim=new THREE.Mesh(new THREE.TorusGeometry(2.03,.018,6,72),new THREE.MeshBasicMaterial({color:'#d7f9ed',transparent:true,opacity:.55}));root.add(rim);
 const graph=new THREE.Group();root.add(graph);const label=document.createElement('button');label.className='world-label';label.style.borderBottomColor=team.color;label.onclick=()=>visit(team);$('labels').append(label);const result={root,graph,label,team,rim};teamGraphs.push(result);rebuild(result);return result;
}
function rebuild(view){
 (view.metadataLabels||[]).forEach(x=>x.label.remove());view.metadataLabels=[];
 for(const child of [...view.graph.children]){const at=pickables.indexOf(child);if(at>=0)pickables.splice(at,1);view.graph.remove(child);if(child.isLine)child.geometry.dispose();else child.material.dispose();}
 const nodes=allNodes(view.team),positions=nodes.map((n,i)=>{const a=i*2.39996,y=1-2*(i+.5)/nodes.length,r=Math.sqrt(1-y*y);return new THREE.Vector3(Math.cos(a)*r*1.45,y*1.45,Math.sin(a)*r*1.45);});
 nodes.forEach((node,i)=>{const mesh=new THREE.Mesh(nodeGeo,new THREE.MeshStandardMaterial({color:nodeColors[node.type]||nodeColors.shared,emissive:nodeColors[node.type]||nodeColors.shared,emissiveIntensity:.15,roughness:.4}));mesh.position.copy(positions[i]);mesh.scale.setScalar(node.type==='source'?1.4:1);mesh.userData={team:view.team,node};view.graph.add(mesh);pickables.push(mesh);const label=document.createElement('button');label.className='metadata-label';label.textContent=node.title;label.title=node.url||node.note;label.onclick=()=>{if(selected!==view.team)visit(view.team);tab(true);showNode(node);$('nodeDetail').scrollIntoView({block:'nearest'});};label.onpointerdown=e=>{e.stopPropagation();label.onclick();};$('labels').append(label);view.metadataLabels.push({label,mesh});});
 const pairs=[...view.team.links];for(let i=view.team.nodes.length;i<nodes.length;i++)pairs.push([i,i%4]);for(const [a,b] of pairs){if(!positions[a]||!positions[b])continue;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([positions[a],positions[b]]),edgeMaterial);view.graph.add(line);}
 view.label.replaceChildren();const mode=document.createElement('em');mode.textContent=view.team.mode;const title=document.createElement('strong');title.textContent=view.team.name;const quote=document.createElement('p');quote.className='team-quote';quote.textContent='A conversation is taking shape…';const count=document.createElement('small');count.textContent=nodes.length+' retained notes · '+pairs.length+' connections';view.label.append(mode,title,quote,count);
}
for(const t of teams){graphFor(t);for(let i=0;i<3;i++){const angle=(i/3)*Math.PI*2+.3;const a=makeClayAgent({id:t.id+'-agent-'+i,name:t.talk[i][0].split(' · ')[0],role:t.talk[i][0].split(' · ')[1],color:[t.color,'#34cab5','#bc73de'][i],prop:['lens','book','scroll'][i]});a.scale.setScalar(.85);a.position.set(t.x+Math.cos(angle)*2.8,.1,t.z+Math.sin(angle)*2.4);a.rotation.y=Math.atan2(t.x-a.position.x,t.z-a.position.z);a.userData.team=t;a.userData.member=i;const speech=document.createElement('button');speech.className='garden-speech';speech.hidden=true;speech.onclick=()=>{visit(a.userData.team);tab(false);};$('labels').append(speech);a.userData.speech=speech;a.userData.base=a.position.clone();a.userData.phase=rand()*10;scene.add(a);octopi.push(a);}}
// Suspended bubbles make the space feel inhabited without expensive particle lights.
const bubbleGeometry=new THREE.SphereGeometry(.08,8,6),bubbleMaterial=new THREE.MeshBasicMaterial({color:'#d6f3ec',transparent:true,opacity:.35});const bubbles=new THREE.InstancedMesh(bubbleGeometry,bubbleMaterial,160);const particlePositions=Array.from({length:160},()=>new THREE.Vector3((rand()-.5)*65,rand()*16,(rand()-.5)*60));scene.add(bubbles);const dummy=new THREE.Object3D();
let selected=null,paused=false,flight=null,pilot=null;const followOffset=new THREE.Vector3(0,5,10);const keys=new Set(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
function fly(target,position){flight={from:camera.position.clone(),start:controls.target.clone(),target,position,elapsed:0};}
function visit(t){releasePilot();selected=t;renderDetails();$('inspector').hidden=false;teamGraphs.forEach(v=>v.label.classList.toggle('selected',v.team===t));const offset=innerWidth>800?new THREE.Vector3(1,1.2,0):new THREE.Vector3(0,1.2,0);fly(new THREE.Vector3(t.x,t?2:0,t.z).add(offset),new THREE.Vector3(t.x+7,10,t.z+19));$('worldStatus').textContent=t.name+' · click a graph node to read its retained note';}
function tab(graph){$('chatPane').hidden=graph;$('graphPane').hidden=!graph;$('chatTab').setAttribute('aria-pressed',String(!graph));$('graphTab').setAttribute('aria-pressed',String(graph));}
function renderDetails(){const t=selected;$('podPilots').replaceChildren();for(const a of octopi.filter(a=>a.userData.team===t)){const b=document.createElement('button');b.textContent='Swim as '+a.userData.agent.name;b.onclick=()=>takeControl(a);$('podPilots').append(b);}$('teamMode').textContent='DEMO TEAM / '+t.mode;$('teamName').textContent=t.name;$('teamBrief').textContent=t.brief;$('chatPane').replaceChildren();for(const [i,[name,text]] of t.talk.entries()){const article=document.createElement('article');article.className='chat-bubble';article.style.background=['#e2eee2','#f5e4d0','#eddfed'][i%3];const b=document.createElement('b');b.textContent=name;const p=document.createElement('p');p.textContent=text;const small=document.createElement('small');small.textContent='Prefilled discussion · illustrative';article.append(b,p,small);voice.addListen(article,text,name);$('chatPane').append(article);}
 if(t.added.length){const p=document.createElement('p');p.textContent=t.added.length+' notes from other teams or your saved research are retained in this bubble.';$('chatPane').append(p);}
 $('shareTarget').replaceChildren();for(const other of teams.filter(x=>x!==t)){const option=document.createElement('option');option.value=other.id;option.textContent=other.name;$('shareTarget').append(option);}$('shareStatus').textContent='Sharing combines notes locally in this demo garden.';$('knowledgeStats').textContent=allNodes(t).length+' retained notes · '+(t.links.length+t.added.length)+' relationships';$('nodeList').replaceChildren();allNodes(t).forEach(node=>{const b=document.createElement('button');b.textContent=node.title;const small=document.createElement('small');small.textContent=node.origin+' · '+node.type;b.append(small);b.onclick=()=>{showNode(node);$('nodeDetail').scrollIntoView({block:'nearest'});};$('nodeList').append(b);});showNode(allNodes(t)[0]);}
function showNode(node){octopi.find(a=>a.userData.team===selected)?.userData.waterSound?.('pop');$('nodeDetail').replaceChildren();const b=document.createElement('b');b.textContent=node.title;const p=document.createElement('p');p.textContent=node.note;const small=document.createElement('small');small.textContent='Retained from '+node.origin;$('nodeDetail').append(b,p,small);if(node.url){try{const url=new URL(node.url);if(['https:','http:'].includes(url.protocol)){const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.className='citation-link';link.textContent='Open source ↗ '+url.hostname;const address=document.createElement('p');address.className='source-url';address.textContent=url.href;const citation=document.createElement('p');citation.textContent=node.citation||((node.publisher||node.origin)+'. '+node.title+'. '+url.href);const copy=document.createElement('button');copy.textContent='Copy citation';copy.onclick=async()=>{try{await navigator.clipboard.writeText(citation.textContent);copy.textContent='Citation copied';}catch{copy.textContent='Select the citation above to copy';}};$('nodeDetail').append(link,address,citation,copy);}}catch{}}else{const info=document.createElement('p');info.textContent='Authored demo note. No external source is attached to this claim.';$('nodeDetail').append(info);}for(const v of teamGraphs)for(const mesh of v.graph.children)if(mesh.isMesh)mesh.material.emissiveIntensity=mesh.userData.node.id===node.id?.9:.15;}
$('chatTab').onclick=()=>tab(false);$('graphTab').onclick=()=>tab(true);$('closeInspector').onclick=()=>{$('inspector').hidden=true;};$('overview').onclick=()=>{releasePilot();flight=null;selected=null;$('inspector').hidden=true;teamGraphs.forEach(v=>v.label.classList.remove('selected'));fly(new THREE.Vector3(0,1,-3),new THREE.Vector3(30,31,41));$('worldStatus').textContent='Four teams · one growing garden';};$('motion').onclick=()=>{paused=!paused;$('motion').textContent=paused?'Resume swimming':'Pause swimming';};
$('shareKnowledge').onclick=()=>{const target=teams.find(t=>t.id===$('shareTarget').value);const existing=new Set(allNodes(target).map(n=>n.id));const incoming=allNodes(selected).filter(n=>!existing.has(n.id)).slice(0,Math.max(0,24-target.added.length));const next=[...target.added,...incoming.map(n=>({...n,type:'shared'}))];try{localStorage.setItem(STORE,JSON.stringify({...shared,[target.id]:next}));shared[target.id]=next;target.added=next;rebuild(teamGraphs.find(v=>v.team===target));octopi.find(a=>a.userData.team===target)?.userData.waterSound?.('appear');$('shareStatus').textContent=incoming.length?'Shared '+incoming.length+' notes with '+target.name+'. Their graph has grown.':'No new notes to combine, or this demo bubble is full.';$('worldStatus').textContent=selected.name+' → '+target.name+' · '+incoming.length+' shared notes retained';}catch{$('shareStatus').textContent='Browser storage is unavailable. Knowledge was not saved.';}};
$('continueResearch').onclick=()=>{sessionStorage.setItem('panel-question',selected.topic);sessionStorage.removeItem('panel-resume');location.href='panel.html?mode=research';};
for(const t of teams){const b=document.createElement('button');const dot=document.createElement('i');dot.style.background=t.color;const label=document.createElement('span');label.textContent=t.name;const small=document.createElement('small');small.textContent=t.mode.toLowerCase();label.append(small);b.append(dot,label);b.onclick=()=>visit(t);$('destinations').append(b);}
$('inspector').hidden=true;let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(pickables);const hit=hits.find(h=>h.object.userData.node)||hits[0];if(hit){const {team,node}=hit.object.userData;visit(team);if(node){tab(true);showNode(node);$('nodeDetail').scrollIntoView({block:'nearest'});}}});controls.addEventListener('start',()=>flight=null);
function clearMovement(){keys.clear();document.querySelectorAll('[data-swim]').forEach(b=>b.classList.remove('held'));}
addEventListener('keydown',e=>{if(e.key==='Escape'){releasePilot();return;}if(e.target.closest('input,textarea,select,[contenteditable=true]')||document.querySelector('dialog[open]'))return;const key=movementKey(e);if(key){keys.add(key);e.preventDefault();flight=null;}});
addEventListener('keyup',e=>{const key=movementKey(e);if(key)keys.delete(key);});addEventListener('blur',clearMovement);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearMovement();});document.addEventListener('focusin',e=>{if(e.target.closest('input,textarea,select,[contenteditable=true]'))clearMovement();});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function joinPod(a){
 if(!a.userData.agent)return;
 const nearest=teams.reduce((best,t)=>Math.hypot(a.position.x-t.x,a.position.z-t.z)<Math.hypot(a.position.x-best.x,a.position.z-best.z)?t:best,teams[0]);
 if(nearest===a.userData.team||Math.hypot(a.position.x-nearest.x,a.position.z-nearest.z)>7)return;
 const origin=a.userData.team,name=a.userData.agent.name;
 a.userData.team=nearest;a.userData.member=nearest.talk.length;const option=[...$('moveOctopus').options].find(o=>o.value===a.name);if(option)option.textContent=name+' · '+nearest.name;
 const intro=`${name} joined from ${origin.name}. I can bring our work on ${origin.ideas[0].toLowerCase()} into this discussion. What connections should we explore?`;
 const reply=`Welcome, ${name}. Let's compare that with ${nearest.ideas[0].toLowerCase()} and keep the original sources attached.`;
 const host=octopi.find(o=>o!==a&&o.userData.team===nearest)?.userData.agent.name||nearest.name;nearest.talk.push([name+' · Visiting collaborator',intro],[host+' · Host',reply]);
 a.userData.speech.textContent=intro;a.userData.speech.dataset.spoken='yes';
 const node={id:'visit-'+Date.now(),title:name+' joined the pod',type:'shared',origin:origin.name,note:intro+' '+reply};nearest.added.push(node);if(nearest.added.length>24)nearest.added.shift();
 rebuild(teamGraphs.find(v=>v.team===nearest));visit(nearest);tab(false);voice.auto(intro,name);a.userData.waterSound?.('appear');
}
const grab=clayGrab({scene,camera,controls,canvas:renderer.domElement,objects:[...movable,...octopi,...octopi.flatMap(a=>a.userData.tentacles.map(arm=>arm.userData.heldTool).filter(Boolean))],bounds:34,floor:0,onDrop:joinPod,onTap:a=>{if(a.userData.team)visit(a.userData.team);},status:text=>{$('worldStatus').textContent=text;},onPickup:()=>{releasePilot();flight=null;}});
for(const a of octopi){const option=document.createElement('option');option.value=a.name;option.textContent=a.userData.agent.name+' · '+a.userData.team.name;$('moveOctopus').append(option);}
for(const t of teams){const option=document.createElement('option');option.value=t.id;option.textContent=t.name;$('movePod').append(option);}
$('moveToPod').onclick=()=>{releasePilot();const a=octopi.find(o=>o.name===$('moveOctopus').value),t=teams.find(t=>t.id===$('movePod').value);grab.place(a,new THREE.Vector3(t.x+2,4,t.z+2));};
const pilotRing=new THREE.Mesh(new THREE.TorusGeometry(1.55,.045,8,64),new THREE.MeshBasicMaterial({color:'#fff19a',transparent:true,opacity:.85}));pilotRing.rotation.x=-Math.PI/2;pilotRing.visible=false;scene.add(pilotRing);
function releasePilot(){if(!pilot)return;pilot.userData.base.copy(pilot.position);pilot.userData.possessed=false;pilot=null;clearMovement();pilotRing.visible=false;$('pilotHud').hidden=true;document.body.classList.remove('piloting');$('worldStatus').textContent='Free exploration · drag water to orbit';}
function takeControl(a){if(!a)return;releasePilot();grab.settle(a);pilot=a;a.userData.possessed=true;a.userData.base.copy(a.position);flight=null;clearMovement();selected=null;$('inspector').hidden=true;teamGraphs.forEach(v=>v.label.classList.remove('selected'));followOffset.set(0,5,10);$('pilotSelect').value=a.name;$('pilotName').textContent='Swimming as '+a.userData.agent.name;$('pilotHud').hidden=false;document.body.classList.add('piloting');pilotRing.visible=true;$('worldStatus').textContent='WASD / arrows to swim · E to join a nearby pod · Esc to release';$('world').focus({preventScroll:true});}
for(const a of octopi){const option=document.createElement('option');option.value=a.name;option.textContent=a.userData.agent.name+' · '+a.userData.team.name;$('pilotSelect').append(option);}
$('takeControl').onclick=()=>takeControl(octopi.find(a=>a.name===$('pilotSelect').value));$('releasePilot').onclick=releasePilot;
function greetPod(){if(!pilot)return;const a=pilot;joinPod(a);}
$('greetPod').onclick=greetPod;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&pilot&&!e.target.closest('input,textarea,select,[contenteditable=true]')&&!document.querySelector('dialog[open]')){e.preventDefault();greetPod();}});
for(const b of document.querySelectorAll('[data-swim]')){b.onpointerdown=e=>{if(!pilot)return;e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.swim);b.classList.add('held');};const stop=()=>{keys.delete(b.dataset.swim);b.classList.remove('held');};b.onpointerup=b.onpointercancel=b.onlostpointercapture=stop;}
controls.addEventListener('end',()=>{if(pilot)followOffset.copy(camera.position).sub(pilot.position);});
const clock=new THREE.Clock(),projected=new THREE.Vector3();let animationTime=0,armTime=0;
function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.04);if(!paused)animationTime+=dt;const time=animationTime;grab.update(dt);ocean.update(time);
 for(let j=0;j<teams.length;j++){const t=teams[j],turn=Math.floor((time+j*2)/7)%t.talk.length;if(t.turn!==turn){t.turn=turn;const [name,text]=t.talk[turn];if(selected===t)voice.auto(text,name);teamGraphs[j].label.querySelector('.team-quote').textContent=name.split(' · ')[0]+': '+text.slice(0,95)+'…';for(const a of octopi.filter(a=>a.userData.team===t)){const speech=a.userData.speech;if(a.userData.agent.name===name.split(' · ')[0]){speech.textContent=name.split(' · ')[0]+': '+text.slice(0,100)+'…';speech.dataset.spoken='yes';a.userData.waterSound?.('appear');}speech.classList.toggle('speaking',a.userData.agent.name===name.split(' · ')[0]);}}}

 if(flight){flight.elapsed+=dt;const p=Math.min(1,flight.elapsed/1.5),ease=p*p*(3-2*p);camera.position.lerpVectors(flight.from,flight.position,ease);controls.target.lerpVectors(flight.start,flight.target,ease);if(p===1)flight=null;}
 if(keys.size&&!pilot){const move=new THREE.Vector3((keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),0,(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0)).normalize().multiplyScalar(dt*8);move.x=THREE.MathUtils.clamp(controls.target.x+move.x,-35,35)-controls.target.x;move.z=THREE.MathUtils.clamp(controls.target.z+move.z,-35,30)-controls.target.z;camera.position.add(move);controls.target.add(move);}
 if(pilot){
  const direction=swimDirection(keys,{x:controls.target.x-camera.position.x,z:controls.target.z-camera.position.z});
  pilot.position.x=THREE.MathUtils.clamp(pilot.position.x+direction.x*4.5*dt,-34,34);pilot.position.z=THREE.MathUtils.clamp(pilot.position.z+direction.z*4.5*dt,-34,34);
  if(direction.x||direction.z){const angle=Math.atan2(direction.x,direction.z),difference=Math.atan2(Math.sin(angle-pilot.rotation.y),Math.cos(angle-pilot.rotation.y));pilot.rotation.y+=difference*(1-Math.exp(-9*dt));}
  pilot.userData.base.x=pilot.position.x;pilot.userData.base.z=pilot.position.z;
  controls.target.lerp(pilot.position.clone().add(new THREE.Vector3(0,1,0)),1-Math.exp(-7*dt));camera.position.lerp(pilot.position.clone().add(followOffset),1-Math.exp(-5*dt));pilotRing.position.copy(pilot.position);pilotRing.position.y=.06;
  const nearby=teams.find(t=>t!==pilot.userData.team&&Math.hypot(pilot.position.x-t.x,pilot.position.z-t.z)<7);$('greetPod').disabled=!nearby;$('greetPod').textContent=nearby?'Join '+nearby.name+' · E':'Swim near another pod to join';
  $('pilotHud').dataset.x=pilot.position.x.toFixed(2);$('pilotHud').dataset.z=pilot.position.z.toFixed(2);
 }
 controls.update();const updateArms=time-armTime>1/18;if(updateArms)armTime=time;
 for(const a of octopi){if(a.userData.clayMoving||a.userData.sculpting)continue;const p=a.userData.phase;if(a!==pilot)a.position.x=a.userData.base.x+Math.sin(time*.27+p)*1.35+Math.sin(time*.11+p*2)*.32;a.position.y+=(a.userData.base.y+.15+Math.sin(time*.9+p)*.22-a.position.y)*(1-Math.exp(-4*dt));if(a!==pilot)a.position.z=a.userData.base.z+Math.cos(time*.23+p)*1.1;const pulse=Math.pow(Math.max(0,Math.sin(time*2.1+p)),3);a.userData.body.scale.set(1-pulse*.055,1+pulse*.08,1-pulse*.055);a.userData.body.rotation.z=Math.sin(time*.7+p)*.09;a.userData.body.rotation.x=Math.sin(time*2.1+p)*.07;if(a!==pilot){const mates=octopi.filter(m=>m!==a&&m.userData.team===a.userData.team);let cx=0,cz=0;for(const m of mates){cx+=m.position.x;cz+=m.position.z;}if(mates.length){cx/=mates.length;cz/=mates.length;}else{cx=a.userData.team.x;cz=a.userData.team.z;}const glance=Math.sin(time*.5+p)*.24+Math.sin(time*1.1+p*1.4)*.1;const heading=Math.atan2(cx-a.position.x,cz-a.position.z)+glance;a.rotation.y+=Math.atan2(Math.sin(heading-a.rotation.y),Math.cos(heading-a.rotation.y))*(1-Math.exp(-2.4*dt));}const speech=a.userData.speech;if(speech.dataset.spoken){projected.copy(a.position).add(new THREE.Vector3(0,2.35,0)).project(camera);speech.hidden=projected.z>1||camera.position.distanceTo(a.position)>28||!!(selected&&a.userData.team!==selected);speech.style.left=(projected.x*.5+.5)*innerWidth+'px';speech.style.top=(-projected.y*.5+.5)*innerHeight+'px';}if(updateArms&&camera.position.distanceTo(a.position)<34)a.userData.tentacles.forEach((arm,i)=>swimArm(arm,time,p+i*.7,.6));}
 for(const v of teamGraphs){if(selected!==v.team)v.root.position.y=4.5+Math.sin(time*.55+v.team.x)*.15;if(!paused&&selected!==v.team)v.graph.rotation.y+=dt*.13;v.rim.quaternion.copy(camera.quaternion);v.root.updateMatrixWorld(true);for(const item of v.metadataLabels||[]){item.mesh.getWorldPosition(projected);projected.project(camera);item.label.hidden=selected!==v.team||$('graphPane').hidden||projected.z>1||Math.abs(projected.x)>1;item.label.style.left=(projected.x*.5+.5)*innerWidth+'px';item.label.style.top=(-projected.y*.5+.5)*innerHeight+'px';}projected.copy(v.root.position).add(new THREE.Vector3(0,2.5,0)).project(camera);v.label.style.display=projected.z>1||projected.z< -1?'none':'block';v.label.style.left=(projected.x*.5+.5)*innerWidth+'px';v.label.style.top=(-projected.y*.5+.5)*innerHeight+'px';}
 particlePositions.forEach((p,i)=>{dummy.position.set(p.x,(p.y+time*.22)%17,p.z);dummy.updateMatrix();bubbles.setMatrixAt(i,dummy.matrix);});bubbles.instanceMatrix.needsUpdate=true;renderer.render(scene,camera);
}tick();
