const KEY='deepsea-research-v1';
export const starterCollections=[
 {id:'starter-panel',title:'How an expert panel works',question:'How should an education expert panel compare evidence and reach a useful recommendation?',kind:'Starter collection',agent:0,sources:[{title:'Deep Researcher · panel workflow',url:'https://github.com/jayrosen-design/deep-researcher-agent',content:'Original project documentation for four discussion rounds and a moderator synthesis.'}]},
 {id:'starter-navigator',title:'Connect to UF NaviGator',question:'How can I connect a research assistant to UF NaviGator securely?',kind:'Starter collection',agent:1,sources:[{title:'NaviGator API quickstart',url:'https://docs.ai.it.ufl.edu/docs/navigator_toolkit/getting_started/quickstart/',content:'Official instructions for personal keys and API requests.'},{title:'Text generation',url:'https://docs.ai.it.ufl.edu/docs/navigator_toolkit/capabilities/text_generation/',content:'Official chat-completion API documentation.'}]},
 {id:'starter-evidence',title:'Build a source-backed answer',question:'How can an assistant collect web evidence and keep its citations grounded?',kind:'Starter collection',agent:2,sources:[{title:'Tavily search API',url:'https://docs.tavily.com/documentation/api-reference/endpoint/search',content:'Official search documentation, source snippets, and URLs.'},{title:'Deep Researcher · citation validation',url:'https://github.com/jayrosen-design/deep-researcher-agent',content:'Original project documentation for checking citations against gathered sources.'}]},
 {id:'starter-review',title:'Review the research pipeline',question:'What checks should a Reviewer apply before releasing a research report?',kind:'Starter collection',agent:3,sources:[{title:'Deep Researcher architecture',url:'https://github.com/jayrosen-design/deep-researcher-agent',content:'Roles of Strategist, Investigator, Synthesizer, and Reviewer.'}]}
];
export function savedResearch(){try{return JSON.parse(localStorage.getItem(KEY)||'[]');}catch{return [];}}
export function collections(){return [...savedResearch(),...starterCollections];}
export function findResearch(id){return collections().find(x=>x.id===id);}
export function classify(question){const q=question.toLowerCase();return /teach|classroom|student|education|learning/.test(q)?'Education':/model|api|software|code|agent|navigator/.test(q)?'Technology':/design|creative|ux|clay/.test(q)?'Design':'General research';}
export function saveResearch(record){const saved=savedResearch().filter(x=>x.id!==record.id);const safe={...record,category:record.category||classify(record.question),updated:Date.now()};try{localStorage.setItem(KEY,JSON.stringify([safe,...saved].slice(0,12)));window.dispatchEvent(new Event('research-updated'));return true;}catch{return false;}}
export function awardPoints(event,id,amount){let state;try{state=JSON.parse(localStorage.getItem('octopi-points')||'{"total":0,"events":[]}');}catch{state={total:0,events:[]};}const token=event+':'+id;if(!state.events.includes(token)){state.events.push(token);state.total+=amount;localStorage.setItem('octopi-points',JSON.stringify(state));}return state.total;}
export function resumeResearch(record){sessionStorage.setItem('panel-question',record.question);sessionStorage.setItem('panel-resume',record.id);if(document.getElementById('researchWorkspace'))window.dispatchEvent(new CustomEvent('octopi-resume',{detail:{mode:record.mode==='research'?'research':'chat'}}));else location.href='index.html?workspace='+(record.mode==='research'?'research':'chat');}
